'use client';

import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#020a02] text-white selection:bg-green-500/30 overflow-x-hidden font-sans flex flex-col">
      <Navbar />

      {/* TERMS CONTENT */}
      <main className="relative z-10 pt-28 pb-16 px-6 max-w-4xl mx-auto w-full">
        <h1 className="text-3xl md:text-4xl font-bold mb-6">Terms & Usage</h1>
        <p className="text-sm text-gray-500 mb-6">
          Beta version — these terms may evolve before the public launch of NFTPulse.
        </p>

        <div className="space-y-6 text-sm text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">1. Nature of the Service</h2>
            <p>
              NFTPulse provides automation and monitoring tools for NFT markets
              (minting bots, wallet tracking, alerts, etc.). NFTPulse is not an exchange
              platform, nor a financial advisor.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">2. No Investment Advice</h2>
            <p>
              The information, signals, or data generated by NFTPulse are provided for
              informational purposes only. You remain solely responsible for your buying,
              selling, or minting decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">3. Private Keys & Security</h2>
            <p>
              NFTPulse will never ask for your seed phrase. You are entirely responsible for
              the security of your wallets, your private keys, and the devices on which you
              run NFTPulse bots.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">4. Beta Phase & Availability</h2>
            <p>
              The service is currently in beta phase. Features may change, be limited,
              or be interrupted without notice. No guarantee of availability or performance
              is provided during this phase.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">5. Fair Use Policy</h2>
            <p>
              You agree not to use NFTPulse for illegal activities, spamming, or any form
              of attack (DoS, vulnerability exploitation, etc.). NFTPulse reserves the right
              to suspend access in case of clear abuse.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2 text-green-400">6. Changes to Terms</h2>
            <p>
              These terms may be updated as the project evolves. The most recent version
              will always be available on this page.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
